
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.1
    ports:
      - "8181:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_API_BASED_MODULES: "true"
      ENABLE_MODULES: "text2vec-ollama,generative-ollama"
      CLUSTER_HOSTNAME: "node1"
    networks:
      - weaviate-net

  weaviate-cli-host:
    image: ubuntu:22.04
    ports:
      - "2222:22"
    volumes:
      - ./ssh:/root/.ssh
    environment:
      - ROOT_PASSWORD=weaviate123
    command: >
      bash -c "apt-get update &&
      apt-get install -y openssh-server python3-pip &&
      pip install weaviate-client &&
      echo 'root:$$ROOT_PASSWORD' | chpasswd &&
      service ssh start &&
      tail -f /dev/null"
    networks:
      - weaviate-net
    depends_on:
      - weaviate

volumes:
  weaviate_data:

networks:
  weaviate-net:
    driver: bridge