apiVersion: v1
kind: PersistentVolume
metadata:
  name: parser-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/parser-data   # папка внешнего хранения
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parser-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
